(()=>{'use strict';const $=id=>document.getElementById(id),base='https://demtoqsafufzmnhvaykj.supabase.co',endpoint=base+'/functions/v1/admin-drafts',publicKey='sb_publishable_0kdLCpTy7Sf8BKkIU5TOqw_Qaay4gzH';
 let token='',busy=false,dirty=false,pending=null,current=null,rows=[],cursor=null,started=false,conflict=false;
 const status=text=>{$('status').textContent=text;};
 function controls(){const locked=busy||!!pending;for(const id of ['filter','refresh','more'])$(id).disabled=locked||dirty;for(const b of $('records').querySelectorAll('button'))b.disabled=locked||dirty;
  $('notes').disabled=locked;$('approve').hidden=$('reject').hidden=current?.submission.status!=='pending';$('restore').hidden=!current||current.submission.status==='pending';
  for(const id of ['approve','reject','restore'])$(id).disabled=locked||!current||conflict;$('reload').disabled=busy||!current;$('retry').hidden=!pending;$('retry').disabled=busy;}
 async function request(body){const response=await fetch(endpoint,{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({domain:'evidence-review',...body})});let result;try{result=await response.json();}catch{throw Error('The server response could not be confirmed.');}if(!response.ok){const error=Error(result.error||'Could not complete Evidence Review.');error.status=response.status;throw error;}return result;}
 function paint(){ $('records').replaceChildren();for(const row of rows){const button=document.createElement('button');button.textContent=row.item_name+' · '+row.status;button.onclick=()=>load(row.id);$('records').append(button);}controls();}
 async function queue(more=false){if(busy||pending||dirty)return;busy=true;controls();try{const result=await request({action:'list',status:$('filter').value,...(more&&cursor?{before:cursor.created_at,beforeId:cursor.id}:{})});rows=more?[...rows,...result.filter(r=>!rows.some(x=>x.id===r.id))]:result;cursor=result.at(-1)||null;$('more').hidden=result.length<30;paint();status(rows.length+' submissions loaded.');}catch(e){status(e.message);}finally{busy=false;controls();}}
 async function screenshot(path){$('screenshot').hidden=true;$('screenshot').removeAttribute('src');$('image-status').textContent='Screenshot unavailable.';
  if(typeof path!=='string'||!path||path.startsWith('/')||path.includes('\\')||path.split('/').some(p=>p==='..'||p==='.'||!p))return;
  try{const response=await fetch(base+'/storage/v1/object/sign/evidence-submissions/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',signal:AbortSignal.timeout(15000),headers:{apikey:publicKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:600})});if(!response.ok)return;const value=await response.json();if(typeof value.signedURL!=='string'||!value.signedURL.startsWith('/object/sign/evidence-submissions/'))return;$('screenshot').src=base+'/storage/v1'+value.signedURL;$('screenshot').hidden=false;$('image-status').textContent='';}catch{}}
 async function load(id){if(busy||pending||dirty)return;busy=true;controls();try{current=await request({action:'load',submissionId:id});conflict=false;const record=current.submission;$('detail').hidden=false;$('name').textContent=record.item_name;$('metadata').textContent=record.category+' · '+record.status+' · Review revision '+current.version;$('submission-notes').textContent=record.notes||'No submission notes.';$('notes').value=record.review_notes||'';
  $('history').replaceChildren();for(const review of current.history){const li=document.createElement('li');li.textContent=review.previous_status+' → '+review.decision+' · '+new Date(review.reviewed_at).toLocaleString()+' · Recorded reviewer '+review.actor+(review.notes?' · '+review.notes:'');$('history').append(li);}$('history-empty').textContent=current.history.length?'':'No recorded review history yet. Earlier review metadata is retained when a new review is recorded.';await screenshot(record.screenshot_path);status('Loaded saved evidence.');$('name').focus();return true;}catch(e){status(e.message);return false;}finally{busy=false;controls();}}
 async function save(){if(busy||!pending)return;busy=true;controls();try{await request(pending);pending=null;dirty=false;const id=current.submission.id;busy=false;const reloaded=await load(id);if(reloaded)await queue();status(reloaded?'Review recorded privately. Nothing published.':'Review recorded privately. Reload saved state before another decision.');}catch(e){if(e.status===400||e.status===409){pending=null;dirty=true;conflict=e.status===409;}status(e.message+' Your review notes are retained.');}finally{busy=false;controls();}}
 function decide(decision){if(busy||pending||!current||conflict)return;if(!confirm((decision==='pending'?'Restore to pending':decision==='approved'?'Approve':'Reject')+' '+current.submission.item_name+'? This records a private review and retains the submission.'))return;pending={action:'decide',submissionId:current.submission.id,requestId:crypto.randomUUID(),expectedVersion:current.version,expectedStatus:current.submission.status,decision,notes:$('notes').value||null};save();}
 $('approve').onclick=()=>decide('approved');$('reject').onclick=()=>decide('rejected');$('restore').onclick=()=>decide('pending');$('retry').onclick=save;$('notes').oninput=()=>{dirty=true;controls();};$('filter').onchange=()=>queue();$('refresh').onclick=()=>queue();$('more').onclick=()=>queue(true);
 $('reload').onclick=()=>{if(busy||!current)return;if((dirty||pending)&&!confirm('Reload the saved evidence? Local review notes and the retry action will be cleared; saved history is retained.'))return;pending=null;dirty=false;load(current.submission.id);};
 window.addEventListener('beforeunload',event=>{if(dirty||pending){event.preventDefault();event.returnValue='';}});
 window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin||event.data?.type!=='scavland-admin-token'||typeof event.data.token!=='string')return;token=event.data.token;if(!started){started=true;$('workspace').hidden=false;queue();}});
 $('screenshot').onerror=()=>{$('screenshot').hidden=true;$('image-status').textContent='Screenshot unavailable.';};
 controls();if(parent!==window)parent.postMessage({type:'scavland-admin-ready'},location.origin);
})();
