const cors={"Access-Control-Allow-Origin":"https://scavlandfanbase.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_ANON_KEY")!,TOKEN=Deno.env.get("GITHUB_TOKEN")!,repo="scavlandfanbase/scavlandfanbase.github.io",filePath="data/site-settings.json";
const allowedPages=new Set(["index.html","vendors.html","weapons.html","armour.html","crafting.html","map.html","items.html","factions.html","areas.html","roadmap.html"]),allowedFields=new Set(["backgroundImage","headerImage","subtitle","fontFamily","fontSize","accentColor","textColor","panelColor","navColor","radius"]);
const gh=()=>({Accept:"application/vnd.github+json",Authorization:`Bearer ${TOKEN}`,"X-GitHub-Api-Version":"2022-11-28"});
const decode=(s:string)=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\n/g,"")),x=>x.charCodeAt(0)));const encode=(s:string)=>{let v="";for(const x of new TextEncoder().encode(s))v+=String.fromCharCode(x);return btoa(v)};
const image=(v:unknown)=>typeof v==="string"&&/^(images|evidence-inbox)\/(?:[A-Za-z0-9._ ()-]+\/)*[A-Za-z0-9._ ()-]+\.(png|jpe?g|webp)$/i.test(v)&&!v.includes("..");
async function admin(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return false;const u=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:auth}});if(!u.ok)return false;const r=await fetch(`${SB}/rest/v1/rpc/is_scavland_admin`,{method:"POST",headers:{apikey:KEY,Authorization:auth,"Content-Type":"application/json"},body:"{}"});return r.ok&&await r.json()===true}
function valid(values:unknown){if(!values||typeof values!=="object"||Array.isArray(values))return false;const data=values as Record<string,unknown>;if(Object.keys(data).some(k=>!allowedFields.has(k)))return false;return (!('backgroundImage'in data)||image(data.backgroundImage))&&(!('headerImage'in data)||image(data.headerImage))&&(!('subtitle'in data)||(typeof data.subtitle==="string"&&data.subtitle.length<=100))&&(!('fontFamily'in data)||(typeof data.fontFamily==="string"&&/^[A-Za-z ,'-]{3,100}$/.test(data.fontFamily)))&&(!('fontSize'in data)||(typeof data.fontSize==="string"&&/^\d{1,2}px$/.test(data.fontSize)))&&(['accentColor','textColor','panelColor','navColor'].every(key=>!(key in data)||(typeof data[key]==="string"&&/^#[0-9A-Fa-f]{6}$/.test(data[key]))))&&(!('radius'in data)||(typeof data.radius==="string"&&/^\d{1,2}px$/.test(data.radius)))}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"POST is required."},405);if(!TOKEN||!SB||!KEY)return out({error:"Publish service is not configured."},503);if(!await admin(req))return out({error:"Authorized SCAVLAND admin access is required."},403);let body:any;try{body=await req.json()}catch{return out({error:"Request must be valid JSON."},400)}if(!valid(body?.settings)||!body.scope||!(body.scope==="global"||allowedPages.has(body.scope)))return out({error:"Invalid site settings update."},400);const current=await fetch(`https://api.github.com/repos/${repo}/contents/${filePath}?ref=main`,{headers:gh()});if(!current.ok)return out({error:"Could not read current settings."},502);const f=await current.json();let doc:any;try{doc=JSON.parse(decode(f.content))}catch{return out({error:"Current settings are invalid JSON."},502)}if(body.scope==="global")doc.global={...doc.global,...body.settings};else doc.pages={...doc.pages,[body.scope]:{...(doc.pages?.[body.scope]||{}),...body.settings}};const put=await fetch(`https://api.github.com/repos/${repo}/contents/${filePath}`,{method:"PUT",headers:{...gh(),"Content-Type":"application/json"},body:JSON.stringify({message:`Update site settings: ${body.scope}`,content:encode(JSON.stringify(doc,null,2)+"\n"),sha:f.sha,branch:"main"})});if(!put.ok)return out({error:"GitHub did not accept the settings update."},502);const result=await put.json();return out({commitUrl:result.commit?.html_url||null})});
